--2.1 SELECT
--SELECT * FROM CHINOOK.EMPLOYEE;
--SELECT * FROM CHINOOK.EMPLOYEE WHERE LASTNAME = 'King';
--SELECT * FROM CHINOOK.EMPLOYEE WHERE FIRSTNAME ='Andrew' AND REPORTSTO =NULL;

--2.2 ORDER BY
--SELECT TITLE FROM CHINOOK.ALBUM ORDER BY TITLE DESC;
--SELECT FIRSTNAME FROM CHINOOK.CUSTOMER ORDER BY FIRSTNAME ASC;

--2.3 
--INSERT INTO CHINOOK.GENRE VALUES(26,'TRENT');
--INSERT INTO CHINOOK.GENRE VALUES(27,'dark techno');
--INSERT INTO CHINOOK.GENRE VALUES(28,'horrorcore');



SELECT * FROM
--2.4
